### ISSUE TITLE
Running the example plugin with Visual Studio 2015

### ISSUE THREAD

**Issue by leonardohra** [xanderdunn/skaar#31]
Hello, I'm trying to use the example plugin, so I've downloaded it (https://github.com/xanderdunn/skaar/releases/download/plugin3/plugin_example3.zip) and tried to run on my Visual Studio 2015 (since I can't download 2013), and it gives an error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy "C:\Users\L\Downloads\Skyrim Plugin\plugin_example\Debug\skse.lib" "\skse.lib"
:VCEnd" exited with code 1.	skse	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	

![vs 2015 erro](https://cloud.githubusercontent.com/assets/3878051/25068309/b0d01718-2235-11e7-83f2-aaa07f819372.png)

Can anyone help me with this error? 
Thanks in advance.

**Comment by leonardohra** [comment]
Nevermind, I just had to run my Visual Studio as Administrator, my bad.

**Comment by xanderdunn** [comment]
@leonardohra Glad you figured it out, I haven't taken a look at Skyrim modding in years, I might come back and do some modding soon though!  ;)

**Comment by Scrivener07** [comment]
Thats a good idea!
